name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: .github/workflows/build_release.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./toml2json_*
            SHA256.txt

  release_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSVC and bazel
      shell: cmd
      run: |
        choco install bazelisk --no-progress
        bazel --version

    - name: Build
      run: .github/workflows/build_release.bat

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          toml2json_windows.exe
          SHA256.txt
